site_name: DNS 53
site_description: Dynamic DNS within Amazon Route53. Expose your EC2 quickly, easily and privately
copyright: Always thinking. Forever learning. 💡
# Only set during a release to ensure htmltest doesn't break due to non existent directories
site_url: ""
repo_name: purpleclay/dns53
repo_url: https://github.com/purpleclay/dns53
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    primary: deep purple
    accent: purple
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Getting Started:
      - Installation: install.md
      - Broadcast your EC2: configure/broadcast-ec2.md
      - Custom Domain: configure/custom-domain.md
      - Expose EC2 Tags: configure/exposing-tags.md
      - IAM: configure/iam.md
  - Reference:
      - Templating: reference/templating.md
      - CLI:
          - dns53: reference/cli/dns53.md
          - dns53 imds: reference/cli/dns53-imds.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/purpleclay
      name: Purple Clay on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/purpleclaydev
      name: Purple Clay on Twitter
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/purpleclay
      name: Purple Clay on Docker Hub
  analytics:
    provider: google
    property: !ENV GH_GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://forms.gle/LfBReL2MUPnwUve6A" target=_blank>feedback form</a>.
  status:
    new: New Feature
    deprecated: No Longer Supported

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: purpleclay/dns53
      token: !ENV GH_TOKEN

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - meta
  - toc:
      permalink: true
