site_name: dns53
site_description: Dynamic DNS within Amazon Route53. Expose your EC2 quickly, easily and privately
copyright: Always thinking. Forever learning. 💡
repo_name: purpleclay/dns53
repo_url: https://github.com/purpleclay/dns53
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    primary: deep purple
    accent: purple
  features:
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - install.md
  - Quick Start: quickstart.md
  - Usage:
      - IAM: iam.md
      - Command Line: cli.md
      - Go Templates: template.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/purpleclay
      name: Purple Clay on GitHub
  analytics:
    provider: google
    property: !ENV GH_GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://forms.gle/LfBReL2MUPnwUve6A" target=_blank>feedback form</a>.

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: purpleclay/dns53
      token: !ENV GH_TOKEN

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - meta
  - toc:
      permalink: true
