# https://taskfile.dev

version: "3"

vars:
  BINDIR: bin
  BINNAME: dns53
  REPORTDIR: reports
  GIT_COMMIT:
    sh: git rev-parse HEAD
  GIT_SHA:
    sh: git rev-parse --short HEAD
  GIT_BRANCH:
    sh: git branch --show-current
  LDFLAGS: >
    -X github.com/purpleclay/dns53/cmd.version=dev-{{.GIT_SHA}}
    -X github.com/purpleclay/dns53/cmd.gitCommit={{.GIT_COMMIT}}
    -X github.com/purpleclay/dns53/cmd.gitBranch={{.GIT_BRANCH}}
    -X github.com/purpleclay/dns53/cmd.buildDate={{now | date "2006-01-02T15:04:05Z07:00"}}

tasks:
  default:
    desc: Runs all of the default tasks
    cmds:
      - task: lint
      - task: test
      - task: integration-test
      - task: build

  build:
    desc: Build the dns53 binary
    cmds:
      - go build -ldflags '-s -w {{.LDFLAGS}}' .

  reports-dir:
    desc: Creates the report directory if it doesn't exist
    cmds:
      - mkdir -p {{.REPORTDIR}}
    status:
      - test -d {{.REPORTDIR}}

  test:
    desc: Run the tests
    deps: [reports-dir]
    cmds:
      - go test -short -race -vet=off -p 1 -covermode=atomic -coverprofile={{.REPORTDIR}}/unittest.out -json ./... | tee {{.REPORTDIR}}/unittest.json

  integration-test:
    desc: Run the integration tests
    deps: [reports-dir]
    cmds:
      - go test -run=Integration -race -vet=off -p 1 -covermode=atomic -coverprofile={{.REPORTDIR}}/integrationtest.out -json ./... | tee {{.REPORTDIR}}/integrationtest.json

  lint:
    desc: Lint the code using golangci
    cmds:
      - golangci-lint run --timeout 5m0s --out-format checkstyle | tee {{.REPORTDIR}}/golangci-lint.xml

  format:
    desc: Format the code using Gofumpt
    cmds:
      - gofumpt -w -l .

  clean:
    desc: Delete all artefacts from recent build
    cmds:
      - task: remove-binary
      - task: remove-reports

  remove-binary:
    desc: Delete an existing built binary
    cmds:
      - rm -f ./{{.BINNAME}}

  remove-reports:
    desc: Delete an existing reports directory
    cmds:
      - rm -rf {{.REPORTDIR}}
