# Copyright (c) 2022 Purple Clay
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# in the Software without restriction, including without limitation the rights
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - purpleclay
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Please be as descriptive and concise as possible. We value all input from the community.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what happened.
      placeholder: Tell us what happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce it
      description: Please list all of the steps taken to reproduce this bug.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Which version?
      description: Which version of dns53 are you using? `dns53 version --short`
      placeholder: dns53 version
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which operating system(s) are you using?
      multiple: true
      options:
        - Linux
        - Mac
        - Windows
        - All
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/purpleclay/dns53/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
